modLoader="javafml" #mandatory

loaderVersion="[26,)" #mandatory (24 is current forge version)

credits="Thanks to Harry Talks for his amazing tutorials." #optional

authors="kwpugh" #optional

[[mods]] #mandatory
modId="gobber2" #mandatory
version="2.1.19" #mandatory
displayName="Gobber 2" #mandatory
description='''
Gobber into 1.14.2, a new beginning!
'''


[[dependencies.gobber2]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[26,)" #mandatory
    ordering="NONE"
    side="BOTH"


# Here's another dependency
[[dependencies.gobber2]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.2]"
    ordering="NONE"
    side="BOTH"
